[package]
name = "aesthetics"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
image = "0.12.3"
timber = { path = "../timber" }
qualia = { path = "../qualia" }

[lib]
name = "aesthetics"
path = "aesthetics.rs"

